require("plugins-setup")

require("core.options")
require("core.keymaps")
require("core.colorscheme")

require("plugins.lualine")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.bufferline")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.copilot")

require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
